name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws-access-key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: docker-react
          environment_name: Docker-react-env
          version_label: ${{ github.sha}}
          region: ap-south-1
          deployment_package: deploy.zip
